### ISSUE TITLE
Confusing and wrong names

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/mzData#3]
@maasencioh 

There are two issues related to the name of this project:

- It is not reading mzML but mzData. So it should be named mzData.
- The npm name has a typo. Furthermore, it should not include a "js" suffix. We propose to use `mzdata`

**Comment by maasencioh** [comment]
`mzData` and `mzXML` are deprecated projects and the idea is to add those formats to this project, avoiding code replication and simplifying its integration with `chromatography`

**Comment by lpatiny** [comment]
Did you have a look about how different those formats are ?

**Comment by maasencioh** [comment]
Both are quite similar in the fact that both use XML tags to organize and base64 to compress, but in any case, it didn't seem trivial how to reutilize the code for both
